USE CursoSQL
GO

/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW GABP.vwTarea5 AS
(
SELECT
	[MATRICULA]
	,[ORGANIZACION]
	,IIF([CATEGORIA] = 'N/A', NULL, [CATEGORIA]) AS [CATEGORIA]
	,[EST-MATRICULA]
	,[RAZON SOCIAL]
	,TRY_CAST(LEFT(REPLACE([FEC-MATRICULA],',',''),4) +'-'+ SUBSTRING(REPLACE([FEC-MATRICULA],',',''),5,2) +'-'+ RIGHT(REPLACE([FEC-MATRICULA],',',''),2) AS DATE) AS [FEC-MATRICULA]
	,TRY_CAST(LEFT(REPLACE([FEC-RENOVACION],',',''),4) +'-'+ SUBSTRING(REPLACE([FEC-RENOVACION],',',''),5,2) +'-'+ RIGHT(REPLACE([FEC-RENOVACION],',',''),2) AS DATE) AS [FEC-RENOVACION]
	,CASE
		WHEN [ULT-ANO_REN]=0 THEN NULL
		WHEN REPLACE([ULT-ANO_REN],'.','')=2 THEN CAST(STR(REPLACE([ULT-ANO_REN],'.',''))+'000' AS int)
		WHEN LEN(REPLACE([ULT-ANO_REN],'.',''))=3 THEN CAST(STR(REPLACE([ULT-ANO_REN],'.',''))+'0' AS int)
	ELSE REPLACE([ULT-ANO_REN],'.','')
	END AS [ULT-ANO_REN]
	,TRY_CAST(IIF([FEC-CANCELACION] != 'N/A',LEFT([FEC-CANCELACION],4) +'-'+ SUBSTRING([FEC-CANCELACION],5,2) +'-'+ RIGHT([FEC-CANCELACION],2) ,NULL) AS date) AS [FEC-CANCELACION]
	,TRY_CAST(IIF([FEC-CONSTITUCION] != 'N/A',LEFT([FEC-CONSTITUCION],4) +'-'+ SUBSTRING([FEC-CONSTITUCION],5,2) +'-'+ RIGHT([FEC-CONSTITUCION],2) ,NULL) AS DATE) AS [FEC-CONSTITUCION]
	,REPLACE([DIR-COMERCIAL],'N/A', '') AS [DIR-COMERCIAL]
	,SUBSTRING([MUN-COMERCIAL], CHARINDEX('-',[MUN-COMERCIAL], 1) + 2, (LEN([MUN-COMERCIAL]) - (CHARINDEX('-',[MUN-COMERCIAL], 1) + 1))) AS [MUN-COMERCIAL]
	,IIF([CIIU-1] = 'N/A', NULL, SUBSTRING([CIIU-1], CHARINDEX('**', [CIIU-1], 1)+3, LEN([CIIU-1]) - (CHARINDEX('**', [CIIU-1], 1)+1))) AS [CIIU-1]
	,IIF([CIIU-2] = 'N/A', NULL, SUBSTRING([CIIU-2], CHARINDEX('**', [CIIU-2], 1)+3, LEN([CIIU-2]) - (CHARINDEX('**', [CIIU-2], 1)+1))) AS [CIIU-2]
	,IIF([CIIU-3] = 'N/A', NULL, SUBSTRING([CIIU-3], CHARINDEX('**', [CIIU-3], 1)+3, LEN([CIIU-3]) - (CHARINDEX('**', [CIIU-3], 1)+1))) AS [CIIU-3]
	,IIF([CIIU-4] = 'N/A', NULL, SUBSTRING([CIIU-4], CHARINDEX('**', [CIIU-4], 1)+3, LEN([CIIU-4]) - (CHARINDEX('**', [CIIU-4], 1)-1))) AS [CIIU-4]
	,IIF([ACTIVIDAD] = 'N/A', NULL, [ACTIVIDAD]) AS [ACTIVIDAD]
	--REPLACE([ING-TAM-EMPRESARIAL], 'N/A','$    - 0') AS [ING-TAM-EMPRESARIAL]
	,TRY_CAST(CASE
			WHEN [ING-TAM-EMPRESARIAL] = 'N/A' THEN NULL
			WHEN CHARINDEX('-',[ING-TAM-EMPRESARIAL],1) = 0 THEN LTRIM(RIGHT([ING-TAM-EMPRESARIAL], LEN([ING-TAM-EMPRESARIAL])-1))
	   		WHEN CHARINDEX('-',[ING-TAM-EMPRESARIAL],1) = 6 THEN '0'
	   	END AS MONEY) AS [ING-TAM-EMPRESARIAL]
	,IIF([TAM-EMPRESA] = 'N/A', NULL, [TAM-EMPRESA]) AS [TAM-EMPRESA]
	,[PERSONAL]
	,CAST([ACTIVO-TOTAL] AS MONEY) AS [ACTIVO-TOTAL]
	,IIF([GRUPO-NIIF] = 'N/A', NULL, [GRUPO-NIIF]) AS [GRUPO-NIIF]
	,CASE
		WHEN [ANO-DATOS]=0 THEN NULL
		WHEN LEN(REPLACE([ANO-DATOS],'.',''))=3 THEN TRY_CAST(STR(REPLACE([ANO-DATOS],'.',''))+'0' AS int)
	ELSE REPLACE([ANO-DATOS],'.','')
	END AS [ANO-DATOS]
	,TRY_CAST(IIF([FECHA-DATOS] != '0',LEFT(REPLACE([FECHA-DATOS],',',''),4) +'-'+ SUBSTRING(REPLACE([FECHA-DATOS],',',''),5,2) +'-'+ RIGHT(REPLACE([FECHA-DATOS],',',''),2) ,NULL) AS date) AS [FECHA-DATOS]
	--,IIF(PATINDEX(0,[FECHA-DATOS])=1, NULL,[FECHA-DATOS])
	,TRY_CAST(IIF([FEC-PAG-REN 2018] != 'N/A',LEFT([FEC-PAG-REN 2018],4) +'-'+ SUBSTRING([FEC-PAG-REN 2018],5,2) +'-'+ RIGHT([FEC-PAG-REN 2018],2) ,NULL) AS date) AS [FEC-PAG-REN 2018]
	,TRY_CAST(IIF([FEC-PAG-REN 2019] != 'N/A',LEFT([FEC-PAG-REN 2019],4) +'-'+ SUBSTRING([FEC-PAG-REN 2019],5,2) +'-'+ RIGHT([FEC-PAG-REN 2019],2) ,NULL) AS date) AS [FEC-PAG-REN 2019]
	,TRY_CAST(IIF([FEC-PAG-REN 2020] != 'N/A',LEFT([FEC-PAG-REN 2020],4) +'-'+ SUBSTRING([FEC-PAG-REN 2020],5,2) +'-'+ RIGHT([FEC-PAG-REN 2020],2) ,NULL) AS date) AS [FEC-PAG-REN 2020]
	,TRY_CAST(IIF([FEC-PAG-REN 2021] != 'N/A',LEFT([FEC-PAG-REN 2021],4) +'-'+ SUBSTRING([FEC-PAG-REN 2021],5,2) +'-'+ RIGHT([FEC-PAG-REN 2021],2) ,NULL) AS date) AS [FEC-PAG-REN 2021]
	,TRY_CAST(IIF([FEC-PAG-REN 2022] = 'N/A',NULL,LEFT([FEC-PAG-REN 2022],4) + '-' + SUBSTRING([FEC-PAG-REN 2022],5,2) + '-' + RIGHT([FEC-PAG-REN 2022],2)) AS date) AS [FEC-PAG-REN 2022]
	,IIF([ACTI 2018] = 'N/A', NULL, [ACTI 2018]) AS [ACTI 2018]
	,IIF([ACTI 2019] = 'N/A', NULL, [ACTI 2018]) AS [ACTI 2019]
	,IIF([ACTI 2020] = 'N/A', NULL, [ACTI 2018]) AS [ACTI 2020]
	,IIF([ACTI 2021] = 'N/A', NULL, [ACTI 2018]) AS [ACTI 2021]
	,IIF([ACTI 2022] = 'N/A', NULL, [ACTI 2018]) AS [ACTI 2022]
	,IIF([MOT-CAN] = 'N/A',NULL,[MOT-CAN]) AS [MOT-CAN]
FROM [CursoSQL].[dbo].[vwDatosPractica])
GO
